import localFont from "next/font/local";
import "./globals.css";

const nasalization = localFont({
  src: "/fonts/Nasalization.otf",
  variable: "--font-nasalization",
});

const madeTommyMed = localFont({
  src: "/fonts/MADETOMMYMedium.otf",
  variable: "--font-made-tommy-medium",
});

const madeTommyBold = localFont({
  src: "/fonts/MADETOMMYBold.otf",
  variable: "--font-made-tommy-bold",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${nasalization.variable} ${madeTommyBold.variable} ${madeTommyMed.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
